feat: first iteration of task
brown-ccv/task-ratings pull request #1
Opened 2021-07-01 18:29 UTC by suivo2001

2021-07-01 18:52 UTC, mcmcgrath13 commented on package.json
>    "description": "all-in-one task starter app with jsPsych + React + Electron + psiturk ",
update the description

2021-07-01 18:52 UTC, mcmcgrath13 commented on src/App.jsx
> +    if (data.trial_type!=='image_keyboard_response')
why not send the image keyboard response trial data?

2021-07-01 18:52 UTC, mcmcgrath13 commented on src/timelines/main.js
> +  primaryTimeline.push(countdown(300*(i+1), 300*i));
why does the countdown vary with the trial number? shouldn't this be the same block repeated 5 times?

2021-07-01 18:52 UTC, mcmcgrath13 commented on src/trials/countdown.js
> +        stimulus: blank,
why use a blank image instead of an empty div or similar?

2021-07-01 18:52 UTC, mcmcgrath13 commented on src/trials/enterRating.js
> +            jsPsych.data.write(data)
shouldn't need the `jsPsych.data.write`, just updating data here should do the trick.

2021-07-01 19:17 UTC, suivo2001 commented
@mcmcgrath13 I should have explained the way I did the countdown here. So I basically took the countdown trial from the behavioral-task-library and modified it. In that version, every second the countdown number changes, it's recorded as a new trial, and the data for it is saved. For this task, we count down 30 minutes, so there will be 1800 irrelevant data points saved, and the final json file will be unnecessarily big, so I made the type for the countdown screens as image_keyboard_response and excluded them from the data. I just found a better way to just add a countdown field as true to those pages and exclude those from the end.

2021-07-01 19:20 UTC, suivo2001 commented on src/timelines/main.js
> +  primaryTimeline.push(countdown(300*(i+1), 300*i));
Yunshu said she wanted the countdown from total time for each block, so 30 minutes to 25, then 25 to 20, ...

2021-07-01 19:39 UTC, mcmcgrath13 commented on src/App.jsx
> +    if (data.countdown!==true)
delete the blank image from assets and add a comment on the timeline about the countdown math, otherwise looks good

2021-07-01 20:51 UTC, mcmcgrath13 requested changes

2021-07-01 20:51 UTC, mcmcgrath13 commented on package.json
> +  "description": "ratings task for OCD Patient study",
does this repo need to be private? (cc @mirestrepo )

2021-07-01 20:51 UTC, mcmcgrath13 commented on src/lib/taskUtils.js
> +const sleep = (ms) => {
sleep is already defined in `utils` - import the function from there

2021-07-01 21:09 UTC, mcmcgrath13 approved these changes
I'd have @mirestrepo approve this one too as she has a better sense of the task requirements

2021-07-07 19:12 UTC, mirestrepo approved these changes
I think it's okay to merge this as a first version. There are few questions for Yunshu.

1. Type of field for the 1-10 rating
2. Should we add some padding to the instructions? They seem pretty close to the edged, are other tasks like that?
3. Should the timer be centered or on the top as it is

2021-07-07 19:12 UTC, mirestrepo commented on src/trials/enterRating.js
> +        type: 'survey_text',
I feel we should checking with Yunshu on this. Seems that having a free text field for 1-10 is error prone. I wonder if [jspsych-html-slider-response](https://www.jspsych.org/plugins/jspsych-html-slider-response/) is better

2021-07-07 19:12 UTC, mirestrepo commented on package.json
> +  "description": "ratings task for OCD Patient study",
Nope

2021-07-07 19:34 UTC, mirestrepo requested changes
Change the 1-10 input field to multiple select buttons. I think https://www.jspsych.org/plugins/jspsych-survey-multi-choice/ is the one...

2021-07-07 20:28 UTC, suivo2001 commented
Changed rating to multiple choice, centered the timer.

2021-07-07 21:25 UTC, mirestrepo approved these changes
The css is funky... I'm not sure if it's easy to adjust but the radio buttons are super close to the numbers, and one needs to scroll to see the continue button, if any of those can be changed that would be great. But if not, you can merge and we can ask Yunshu more

2021-07-07 21:25 UTC, mirestrepo commented on src/App.css
> +  height: 95vh;
Can we also adjust the width?

2021-07-07 21:26 UTC, mirestrepo requested changes

2021-07-07 21:26 UTC, mirestrepo commented on src/language/en_us.json
> +    "enter_rating": "Please rate your OCD symptom intensity from 0-10. Press continue to submit your rating.”"
There is an extra closing " that is not needed here

2021-07-07 22:14 UTC, suivo2001 commented
I added a margin for the radio buttons, adjusted the full width and the instructions text. I'm pretty sure when the app is in fullscreen, which the participants should be running the task at, there's plenty of space between the continue button and the bottom, so I don't think its an issue.

2021-07-08 01:24 UTC, mirestrepo approved these changes
Looks great!

2021-07-08 02:56 UTC, merged